Add meta-openembedded/meta-ruby
ruby-native (from meta-ruby) is required by qtwebkit.

Fixes:

ERROR: Nothing PROVIDES 'ruby-native'
  (but /home/mario/src/reach/sources/meta-qt5/recipes-qt/qt5/qtwebkit_5.2.1.bb
  DEPENDS on or otherwise requires it).

Signed-off-by: Mario Domenech Goulart <mario@ossystems.com.br>